[package]
name = "gorce-core"
description = "Core domain contracts for Gorce"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
gorce-provider-abi = { path = "../gorce-provider-abi" }
gorce-protocol = { path = "../gorce-protocol" }
serde_json = "1.0.114"

[lints]
workspace = true
