[package]
name = "gorce"
description = "Gorce command-line application"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
gorce-daemon = { path = "../gorce-daemon" }
gorce-sdk = { path = "../gorce-sdk" }
gorce-tui = { path = "../gorce-tui" }

[lints]
workspace = true
