[package]
name = "gorce"
description = "Gorce command-line application"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
gorce-daemon = { path = "../gorce-daemon" }
gorce-sdk = { path = "../gorce-sdk" }
gorce-tui = { path = "../gorce-tui" }
serde_json = "1.0.114"
tokio = { version = "1.36.0", features = ["macros", "rt-multi-thread", "time"] }

[lints]
workspace = true
