[package]
name = "gorce-sdk"
description = "Client SDK contracts for Gorce"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
gorce-protocol = { path = "../gorce-protocol" }
reqwest = { version = "=0.12.24", default-features = false, features = ["json", "rustls-tls", "stream"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
tokio = { version = "1.36.0", features = ["macros", "rt", "sync", "time"] }
uuid = { version = "1.7.0", features = ["v4", "v7"] }

[lints]
workspace = true
